parameters:
#    poivre_user.example.class: Poivre\UserBundle\Example

services:
#    poivre_user.example:
#        class: %poivre_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
